CREATE TABLE [iSeriesSaled](
	[SeriesCode] [varchar](50) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[MatCode] [dbo].[matcode] NULL,
	[state] [varchar](8) COLLATE Chinese_PRC_CI_AS NULL,
	[stcode] [dbo].[orgcode] NULL,
	[vndcode] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[purprice] [money] NULL,
	[purGRdate] [datetime] NULL,
	[purGRDocCode] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[purReturnDate] [datetime] NULL,
	[purReturnPrice] [money] NULL,
	[purReturnDocCode] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[purSPmoney] [money] NULL,
	[purAchivePrice] [money] NULL,
	[purClearPrice] [money] NULL,
	[payamount] [money] NULL,
	[cltcode] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[SalesDOCCode] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[SalesDate] [datetime] NULL,
	[TermialDate] [datetime] NULL,
	[createdate] [datetime] NULL,
	[createformid] [int] NULL,
	[createdoccode] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[returncode] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[returnname] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[returndate] [datetime] NULL,
	[returndoccode] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[salesprice] [money] NULL,
	[yxdate] [datetime] NULL,
	[UserDigit1] [dbo].[i3money] NULL,
	[sbcmoney] [dbo].[i3money] NULL,
	[gift] [varchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[FK] [dbo].[blfalse] NULL,
	[bgcrttime] [datetime] NULL,
	[reqdoccode] [nvarchar](16) COLLATE Chinese_PRC_CI_AS NULL,
	[bglosttime] [datetime] NULL,
	[isbg] [bit] NULL,
	[isava] [bit] NULL,
	[crtprice] [money] NULL,
	[stcode1] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[station] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[shdjdate] [datetime] NULL,
	[shdjhdmemo] [varchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[salecompanyid] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[isout] [int] NULL,
	[fanli] [money] NULL,
	[Uom] [varchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[issend] [int] NULL,
	[shdjusertxt] [varchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[preAllocation] [bit] NULL,
	[SeriesNumber] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[CashReward] [money] NULL,
	[Occupyed] [bit] NULL,
	[OccupyedDoc] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[salemun] [int] NULL,
	[delint] [int] NULL,
	[areaid] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[areaname] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[PackageID] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[FormGroup] [varchar](200) COLLATE Chinese_PRC_CI_AS NULL,
	[ExtendWarrantyDate] [datetime] NULL,
	[ExtendWarrantyDoc] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[contype] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[plantid] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[isContractSale] [bit] NULL,
	[AreaCode] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[Remark] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[seriestype] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[isPackaged] [bit] NULL,
	[ESSID] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[UNcomID] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[Busitype] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK_iSeriesSaled] PRIMARY KEY CLUSTERED 
(
	[SeriesCode] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100) ON [PRIMARY],
 CONSTRAINT [IX_iSeriesSaled] UNIQUE NONCLUSTERED 
(
	[SeriesCode] ASC,
	[MatCode] ASC,
	[stcode] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

 